### ISSUE TITLE
视频拼接合成

### ISSUE THREAD

**Issue by Jijingcheng** [itdongqiang/AVFoundationProject#1]
视频拼接合成，我2个视频合成后的视频是无声的，不知道为什么，是需要设置什么属性吗？

**Comment by itdongqiang** [comment]
需要合成音频轨道，只合视频是没有声音的。

**Comment by itdongqiang** [comment]
> 视频拼接合成，我2个视频合成后的视频是无声的，不知道为什么，是需要设置什么属性吗？

需要合成音频轨道，只合视频是没有声音的。

**Comment by itdongqiang** [comment]
> 

@Jijingcheng 需要合成音频轨道，只合视频是没有声音的。

**Comment by Jijingcheng** [comment]
> @Jijingcheng 需要合成音频轨道，只合视频是没有声音的。

感谢回复，我就是普通使用，直接用这两个视频的音频就行，有这样的代码示例吗，我现在还不看得不是很懂

**Comment by itdongqiang** [comment]
> > @Jijingcheng 需要合成音频轨道，只合视频是没有声音的。
> 
> 感谢回复，我就是普通使用，直接用这两个视频的音频就行，有这样的代码示例吗，我现在还不看得不是很懂

@Jijingcheng 可以参考一下demo里的TTAVVideoCompositionTool 67-69行，1.添加音频空轨道。2.获取视频文件的音频轨道。3.将音频轨道加入空轨道中。

**Comment by itdongqiang** [comment]
finished
